[programs.localnet]
stead_rent = "TrXDop6spRAwHDsSpvY51PxHkvZXKGNYC6bygXZLNC2"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./key.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
